CREATE VIEW EGOVIEWSESSIONS AS 
SELECT
    EGOSESSIONS.SYSID AS SYSID,
    EGOALIASES.NAME AS USERNAME,
    EGOSESSIONS.BEGINTIME AS BEGINTIME,
    EGOSESSIONS.RENEWALTIME AS RENEWALTIME,
    EGOSESSIONS.ENDTIME AS ENDTIME,
    CASE 
    WHEN (EGOSESSIONS.ENDTIME IS NULL AND [:DATE(EGOSESSIONS.RENEWALTIME, 1DAYS)]>[:TODAY()]) THEN 1 
    ELSE 0 
    END AS ACTIVE
FROM EGOSESSIONS
INNER JOIN EGOALIASES ON EGOALIASES.SYSID=EGOSESSIONS.ALIASID
