CREATE VIEW EGOVIEWUSERS AS 
SELECT
    U1.SYSID AS SYSID,
    U1.USERID AS USERID,
    U1.NAME AS ALIASNAME,
    U2.NAME AS USERNAME,
    U1.EMAIL AS EMAIL,
    EGOUSERS.ACTIVE AS ACTIVE,
    U1.DEMIURGE AS DEMIURGE,
    U1.ADMINISTRATOR AS ADMINISTRATOR
FROM EGOUSERS
INNER JOIN EGOALIASES U1 ON U1.USERID=EGOUSERS.SYSID
INNER JOIN EGOALIASES U2 ON U2.USERID=U1.USERID AND U2.MAIN=1
