CREATE VIEW EGOVIEWENVIRONUSER AS 
SELECT
    EGOENVIRONUSER.SYSID AS SYSID,
    EGOENVIRONUSER.ENVIRONID AS ENVIRONID,
    EGOENVIRONS.APPID AS APPID,
    EGOENVIRONS.NAME AS ENVIRONNAME,
    EGOENVIRONS.DESCRIPTION AS DESCRIPTION,
    EGOALIASES.NAME AS USERNAME,
    EGOUSERS.SYSID AS USERID
FROM EGOENVIRONUSER
INNER JOIN EGOENVIRONS ON EGOENVIRONS.SYSID=EGOENVIRONUSER.ENVIRONID
INNER JOIN EGOUSERS ON EGOUSERS.SYSID=EGOENVIRONUSER.USERID
INNER JOIN EGOALIASES ON EGOALIASES.USERID=EGOUSERS.SYSID 
WHERE
    EGOALIASES.MAIN=1 AND EGOUSERS.ACTIVE=1
