CREATE VIEW QW_ACCREDITIJOIN AS
SELECT 
    QW_ACCREDITI.SYSID AS SYSID, 
    QW_ACCREDITI.DESCRIPTION AS DESCRIPTION,
    QW_ACCREDITI.REGISTRY AS REGISTRY,
    QW_ACCREDITI.REFERENCE AS REFERENCE,
    QW_ACCREDITI.TAG AS TAG,
    QW_ACCREDITI.TYPOLOGYID AS TYPOLOGYID,
    CASE 
    WHEN (QW_ACCREDITI.CORSOID='' OR QW_ACCREDITI.CORSOID IS NULL) THEN 0
    ELSE 1
    END AS FLAGCORSO,
    QW_ACCREDITI.BOWTIME AS BOWTIME,
    QW_ACCREDITI.TARGETID AS TARGETID,
    QW_ACCREDITI.TARGETTIME AS TARGETTIME,
    QW_ACCREDITI.AMOUNT AS AMOUNT,
    QW_ACCREDITI.STATUS AS STATUS,
    QW_ACCREDITI.AVAILABILITY AS AVAILABILITY,
    QW_ACCREDITI.CONSISTENCY AS CONSISTENCY,
    QW_ACCREDITI.TIMEINSERT AS TIMEINSERT,
    QW_ACCREDITI.PHASENOTE AS PHASENOTE,
    QW_ACCREDITI.TIPOCORSO AS TIPOCORSO,
    QW_ACCREDITI.LUOGO AS LUOGO,
    QW_ACCREDITI.REFERENTE AS REFERENTE,
    QW_ACCREDITI.CORSOID AS CORSOID,
    QW_PERSONE.DESCRIPTION AS TARGET,
    QW_CORSI.DESCRIPTION AS CORSO,
    QW_CORSI.REGISTRY AS CORSONOTE,
    QW_AZIENDE.SYSID AS AZIENDAID,
    QW_AZIENDE.DESCRIPTION AS AZIENDA
FROM QW_ACCREDITI
INNER JOIN QW_PERSONE ON QW_PERSONE.SYSID=QW_ACCREDITI.TARGETID
LEFT JOIN QW_CORSI ON QW_CORSI.SYSID=QW_ACCREDITI.CORSOID
LEFT JOIN QW_AZIENDE ON QW_AZIENDE.SYSID=QW_CORSI.AZIENDAID

