CREATE VIEW QW_ARTICOLIJOIN AS
SELECT 
    QW_ARTICOLI.SYSID AS SYSID, 
    QW_ARTICOLI.DESCRIPTION AS DESCRIPTION,
    QW_ARTICOLI.REGISTRY AS REGISTRY,
    QW_ARTICOLI.TYPOLOGYID AS TYPOLOGYID,
    QW_ARTICOLI.ROUNDING AS ROUNDING,
    QW_ARTICOLI.TAG AS TAG,
    QW_ARTICOLI.CODICE AS CODICE,
    QW_ARTICOLI.PRODOTTO AS PRODOTTO,
    QW_ARTICOLI.VARIANTE AS VARIANTE,
    QW_ARTICOLI.PRODUTTOREID AS PRODUTTOREID,
    QW_ARTICOLI.PROCESSOID AS PROCESSOID,
    PRODUTTORI.DESCRIPTION AS PRODUTTORE,
    PROCESSI.DESCRIPTION AS PROCESSO,
    CLASSE.DESCRIPTION AS CLASSE
FROM QW_ARTICOLI
LEFT JOIN QVOBJECTS PRODUTTORI ON PRODUTTORI.SYSID=QW_ARTICOLI.PRODUTTOREID
LEFT JOIN QVQUIVERS PROCESSI ON PROCESSI.SYSID=QW_ARTICOLI.PROCESSOID
LEFT JOIN QVSELECTIONS ON QVSELECTIONS.PARENTID=QW_ARTICOLI.SYSID AND QVSELECTIONS.SORTER=1
LEFT JOIN QVOBJECTS CLASSE ON CLASSE.SYSID=QVSELECTIONS.SELECTEDID
