CREATE VIEW QW_ATTIVITAJOIN AS
SELECT
    QVARROWS.SYSID AS SYSID, 
    QVARROWS.DESCRIPTION AS DESCRIPTION,
    QVARROWS.REGISTRY AS REGISTRY,
    QVARROWS.TYPOLOGYID AS TYPOLOGYID,
    QVARROWS.AUXTIME AS AUXTIME,
    QVARROWS.BOWTIME AS BOWTIME,
    QVARROWS.BOWID AS BOWID,
    QVARROWS.TARGETTIME AS TARGETTIME,
    QVARROWS.TARGETID AS TARGETID,
    QVARROWS.GENREID AS GENREID,
    QVARROWS.AMOUNT AS AMOUNT,
    QVARROWS.MOTIVEID AS MOTIVEID,
    QVARROWS.REFARROWID AS REFARROWID,
    ARROWS_ATTIVITA.IMPORTANZA AS IMPORTANZA,
    ARROWS_ATTIVITA.PERCENTUALE AS PERCENTUALE,
    ARROWS_ATTIVITA.STATOID AS STATOID,
    QVARROWS.SCOPE AS SCOPE,
    QVARROWS.STATUS AS STATUS,
    QVARROWS.UPDATING AS UPDATING,
    QVARROWS.CONSISTENCY AS CONSISTENCY,
    QVARROWS.AVAILABILITY AS AVAILABILITY,
    QVARROWS.REFERENCE AS REFERENCE,
    QVARROWS.TAG AS TAG,
    QVARROWS.TIMEINSERT AS TIMEINSERT,
    QVARROWS.PHASE AS PHASE,
    QW_PROCSTATI.DESCRIPTION AS STATODESCR,
    QW_PROCSTATI.PROCESSOID AS PROCESSOID,
    ATTORIBOW.DESCRIPTION AS BOW,
    ATTORITARGET.DESCRIPTION AS TARGET,
    ATTORITARGET.EGOUTENTEID AS TARGETUTENTEEGO,
    ATTORITARGET.EGORUOLOID AS TARGETRUOLOEGO,
    QW_MOTIVIATTIVITA.DESCRIPTION AS MOTIVE,
    QW_MOTIVIATTIVITA.GANTT AS GANTT,
    QVQUIVERARROW.QUIVERID AS PRATICAID,
    OWNER.DESCRIPTION AS OWNER
FROM QVARROWS
INNER JOIN ARROWS_ATTIVITA ON ARROWS_ATTIVITA.SYSID=QVARROWS.SYSID
INNER JOIN QW_PROCSTATI ON QW_PROCSTATI.SYSID=ARROWS_ATTIVITA.STATOID
LEFT JOIN QVOBJECTS ATTORIBOW ON ATTORIBOW.SYSID=QVARROWS.BOWID
LEFT JOIN QW_ATTORIEGO ATTORITARGET ON ATTORITARGET.SYSID=QVARROWS.TARGETID
INNER JOIN QVOBJECTS OWNER ON OWNER.SYSID=QW_PROCSTATI.ATTOREID
INNER JOIN QW_MOTIVIATTIVITA ON QW_MOTIVIATTIVITA.SYSID=QVARROWS.MOTIVEID
INNER JOIN QVQUIVERARROW ON QVQUIVERARROW.ARROWID=QVARROWS.SYSID
WHERE 
    QVARROWS.TYPOLOGYID=[:SYSID(0ATTIVITA000)] AND QVARROWS.DELETED=0
