CREATE VIEW QW_ACCREDITI AS
SELECT 
    QVARROWS.SYSID AS SYSID, 
    QVARROWS.DESCRIPTION AS DESCRIPTION,
    QVARROWS.REGISTRY AS REGISTRY,
    QVARROWS.REFERENCE AS REFERENCE,
    QVARROWS.TAG AS TAG,
    QVARROWS.TYPOLOGYID AS TYPOLOGYID,
    QVARROWS.BOWTIME AS BOWTIME,
    QVARROWS.TARGETID AS TARGETID,
    QVARROWS.TARGETTIME AS TARGETTIME,
    QVARROWS.AMOUNT AS AMOUNT,
    QVARROWS.STATUS AS STATUS,
    QVARROWS.AVAILABILITY AS AVAILABILITY,
    QVARROWS.CONSISTENCY AS CONSISTENCY,
    QVARROWS.TIMEINSERT AS TIMEINSERT,
    QVARROWS.PHASENOTE AS PHASENOTE,
    ARROWS_ACCREDITI.TIPOCORSO AS TIPOCORSO,
    ARROWS_ACCREDITI.LUOGO AS LUOGO,
    ARROWS_ACCREDITI.REFERENTE AS REFERENTE,
    ARROWS_ACCREDITI.CORSOID AS CORSOID,
    ARROWS_ACCREDITI.MOREDATA AS MOREDATA
FROM QVARROWS 
INNER JOIN ARROWS_ACCREDITI ON ARROWS_ACCREDITI.SYSID=QVARROWS.SYSID 
WHERE 
    QVARROWS.TYPOLOGYID=[:SYSID(0ACCREDITI00)] AND QVARROWS.DELETED=0

