CREATE VIEW QW_ATTIVITABROWSER AS
SELECT DISTINCT
    QVARROWS.SYSID AS SYSID, 
    QVARROWS.DESCRIPTION AS DESCRIPTION,
    QVARROWS.TYPOLOGYID AS TYPOLOGYID,
    QVARROWS.AUXTIME AS AUXTIME,
    QVARROWS.BOWTIME AS BOWTIME,
    QVARROWS.BOWID AS BOWID,
    QVARROWS.TARGETTIME AS TARGETTIME,
    QVARROWS.TARGETID AS TARGETID,
    QVARROWS.GENREID AS GENREID,
    QVARROWS.AMOUNT AS AMOUNT,
    QVARROWS.MOTIVEID AS MOTIVEID,
    CASE
    WHEN QVARROWS.REFARROWID<>'' THEN QVARROWS.REFARROWID
    ELSE QVARROWS.SYSID
    END AS REFARROWID,
    ARROWS_ATTIVITA.IMPORTANZA AS IMPORTANZA,
    ARROWS_ATTIVITA.PERCENTUALE AS PERCENTUALE,
    ARROWS_ATTIVITA.STATOID AS STATOID,
    QVARROWS.SCOPE AS SCOPE,
    QVARROWS.STATUS AS STATUS,
    QVARROWS.CONSISTENCY AS CONSISTENCY,
    QVARROWS.AVAILABILITY AS AVAILABILITY,
    QVARROWS.REFERENCE AS REFERENCE,
    QVARROWS.TAG AS TAG,
    QVARROWS.ROLEID AS ROLEID,
    QVARROWS.USERINSERTID AS USERINSERTID,
    QVARROWS.TIMEINSERT AS TIMEINSERT,
    QW_PROCSTATI.DESCRIPTION AS STATODESCR,
    QW_PROCSTATI.PROCESSOID AS PROCESSOID,
    ATTORIBOW.DESCRIPTION AS BOW,
    ATTORITARGET.DESCRIPTION AS TARGET,
    ATTORITARGET.EGOUTENTEID AS TARGETUTENTEEGO,
    ATTORITARGET.EGORUOLOID AS TARGETRUOLOEGO,
    QW_MOTIVIATTIVITA.DESCRIPTION AS MOTIVE,
    QW_MOTIVIATTIVITA.GANTT AS GANTT,
    QW_MOTIVIATTIVITA.SETCONOSCENZA AS SETCONOSCENZA,
    {L:QVSELECTIONS.SELECTEDID AS SELECTEDID,}
    QVQUIVERARROW.QUIVERID AS PRATICAID,
    OWNER.DESCRIPTION AS OWNER,
    CASE
    WHEN QVTABLEFILE.SYSID IS NULL THEN 0
    ELSE 1
    END AS ALLEGATI,
    CASE
    WHEN QVRISPOSTE.SYSID IS NULL THEN 0
    ELSE 1
    END AS RISPOSTE
FROM QVARROWS
INNER JOIN ARROWS_ATTIVITA ON ARROWS_ATTIVITA.SYSID=QVARROWS.SYSID
INNER JOIN QW_PROCSTATI ON QW_PROCSTATI.SYSID=ARROWS_ATTIVITA.STATOID
LEFT JOIN QVOBJECTS ATTORIBOW ON ATTORIBOW.SYSID=QVARROWS.BOWID
LEFT JOIN QW_ATTORIEGO ATTORITARGET ON ATTORITARGET.SYSID=QVARROWS.TARGETID
INNER JOIN QVOBJECTS OWNER ON OWNER.SYSID=QW_PROCSTATI.ATTOREID
INNER JOIN QW_MOTIVIATTIVITA ON QW_MOTIVIATTIVITA.SYSID=QVARROWS.MOTIVEID
{L:LEFT JOIN QVSELECTIONS ON QVSELECTIONS.PARENTID=QW_MOTIVIATTIVITA.SETCONOSCENZA}
INNER JOIN QVQUIVERARROW ON QVQUIVERARROW.ARROWID=QVARROWS.SYSID
LEFT JOIN QVTABLEFILE ON QVTABLEFILE.RECORDID=QVARROWS.SYSID
LEFT JOIN QVARROWS QVRISPOSTE ON QVRISPOSTE.REFARROWID=QVARROWS.SYSID AND QVRISPOSTE.AVAILABILITY=0 AND QVRISPOSTE.CONSISTENCY=0
WHERE 
    QVARROWS.TYPOLOGYID=[:SYSID(0ATTIVITA000)] AND QVARROWS.DELETED=0
