CREATE VIEW QW_ATTORIJOIN AS
SELECT 
    QW_ATTORI.SYSID AS SYSID, 
    QW_ATTORI.AZIENDAID AS AZIENDAID,
    QW_ATTORI.PROPRIETAID AS PROPRIETAID,
    QW_ATTORI.UFFICIOID AS UFFICIOID,
    QW_ATTORI.PERSONAID AS PERSONAID,
    QW_ATTORI.UTENTEID AS UTENTEID,
    QW_ATTORI.RUOLOID AS RUOLOID,
    QVUSERS.EGOID AS EGOUTENTEID,
    QVUSERS.ADMINISTRATOR AS ADMINISTRATOR,
    QVROLES.EGOID AS EGORUOLOID,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.DESCRIPTION
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.DESCRIPTION
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.DESCRIPTION
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.DESCRIPTION
    ELSE QW_ATTORI.DESCRIPTION
    END AS DESCRIPTION,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.REGISTRY
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.REGISTRY
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.REGISTRY
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.REGISTRY
    ELSE NULL
    END AS REGISTRY,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.INDIRIZZO
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.INDIRIZZO
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.INDIRIZZO
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.INDIRIZZO
    ELSE ''
    END AS INDIRIZZO,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.CIVICO
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.CIVICO
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.CIVICO
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.CIVICO
    ELSE ''
    END AS CIVICO,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.CAP
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.CAP
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.CAP
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.CAP
    ELSE ''
    END AS CAP,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.CITTA
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.CITTA
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.CITTA
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.CITTA
    ELSE ''
    END AS CITTA,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.PROVINCIA
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.PROVINCIA
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.PROVINCIA
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.PROVINCIA
    ELSE ''
    END AS PROVINCIA,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.NAZIONE
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.NAZIONE
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.NAZIONE
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.NAZIONE
    ELSE ''
    END AS NAZIONE,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.INDIRIZZO
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.INDIRIZZO
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.COLLOCAZIONE
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.INDIRIZZO
    ELSE ''
    END AS COLLOCAZIONE,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.EMAIL
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.EMAIL
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.EMAIL
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.EMAIL
    ELSE QW_ATTORI.EMAIL
    END AS EMAIL,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.TELEFONO
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.TELEFONO
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.TELEFONO
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.TELEFONO
    ELSE ''
    END AS TELEFONO,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.CELLULARE
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.CELLULARE
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.CELLULARE
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.CELLULARE
    ELSE ''
    END AS CELLULARE,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.FAX
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.FAX
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.FAX
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.FAX
    ELSE ''
    END AS FAX,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.CONTODEFAULTID
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.CONTODEFAULTID
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.CONTODEFAULTID
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.CONTODEFAULTID
    ELSE ''
    END AS CONTODEFAULTID,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.ABI
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.ABI
    WHEN QW_ATTORI.UFFICIOID<>'' THEN ''
    WHEN QW_ATTORI.PERSONAID<>'' THEN ''
    ELSE ''
    END AS ABI,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.CAB
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.CAB
    WHEN QW_ATTORI.UFFICIOID<>'' THEN ''
    WHEN QW_ATTORI.PERSONAID<>'' THEN ''
    ELSE ''
    END AS CAB,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.PIVA
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.PIVA
    WHEN QW_ATTORI.UFFICIOID<>'' THEN ''
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.PIVA
    ELSE ''
    END AS PIVA,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.CODFISC
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.CODFISC
    WHEN QW_ATTORI.UFFICIOID<>'' THEN ''
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.CODFISC
    ELSE ''
    END AS CODFISC,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.CCIAA
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.CCIAA
    WHEN QW_ATTORI.UFFICIOID<>'' THEN ''
    WHEN QW_ATTORI.PERSONAID<>'' THEN ''
    ELSE ''
    END AS CCIAA,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.ATECO
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.ATECO
    WHEN QW_ATTORI.UFFICIOID<>'' THEN ''
    WHEN QW_ATTORI.PERSONAID<>'' THEN ''
    ELSE ''
    END AS ATECO,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.DESCRIPTION
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.DESCRIPTION
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.DESCRIPTION
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.NOME
    ELSE ''
    END AS NOME,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN ''
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN ''
    WHEN QW_ATTORI.UFFICIOID<>'' THEN ''
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.COGNOME
    ELSE ''
    END AS COGNOME,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN 'F'
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN 'F'
    WHEN QW_ATTORI.UFFICIOID<>'' THEN 'M'
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.SESSO
    ELSE ''
    END AS SESSO,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN ''
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN ''
    WHEN QW_ATTORI.UFFICIOID<>'' THEN ''
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.DOCUMENTO
    ELSE ''
    END AS DOCUMENTO,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN ''
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN ''
    WHEN QW_ATTORI.UFFICIOID<>'' THEN ''
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.TESSERA
    ELSE ''
    END AS TESSERA,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.CITTA
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_AZIENDE.CITTA
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.COLLOCAZIONE
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.LUOGONASCITA
    ELSE ''
    END AS LUOGONASCITA,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.CITTA
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_AZIENDE.CITTA
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.COLLOCAZIONE
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.LUOGOMORTE
    ELSE ''
    END AS LUOGOMORTE,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.BEGINTIME
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.BEGINTIME
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.BEGINTIME
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.BEGINTIME
    ELSE [:DATE(19000101)]
    END AS BEGINTIME,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.ENDTIME
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.ENDTIME
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.ENDTIME
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.ENDTIME
    ELSE [:DATE(99991231)]
    END AS ENDTIME,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.REFERENCE
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.REFERENCE
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.REFERENCE
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.REFERENCE
    ELSE ''
    END AS REFERENCE,
    CASE
    WHEN QW_ATTORI.AZIENDAID<>'' THEN QW_AZIENDE.TAG
    WHEN QW_ATTORI.PROPRIETAID<>'' THEN QW_PROPRIETA.TAG
    WHEN QW_ATTORI.UFFICIOID<>'' THEN QW_UFFICI.TAG
    WHEN QW_ATTORI.PERSONAID<>'' THEN QW_PERSONE.TAG
    ELSE ''
    END AS TAG
FROM QW_ATTORI
LEFT JOIN QW_AZIENDE ON QW_AZIENDE.SYSID=QW_ATTORI.AZIENDAID
LEFT JOIN QW_PROPRIETA ON QW_PROPRIETA.SYSID=QW_ATTORI.PROPRIETAID
LEFT JOIN QW_UFFICI ON QW_UFFICI.SYSID=QW_ATTORI.UFFICIOID
LEFT JOIN QW_PERSONE ON QW_PERSONE.SYSID=QW_ATTORI.PERSONAID
LEFT JOIN QVUSERS ON QVUSERS.SYSID=QW_ATTORI.UTENTEID
LEFT JOIN QVROLES ON QVROLES.SYSID=QW_ATTORI.RUOLOID

