CREATE VIEW QW_ATTORI AS
SELECT 
    QVOBJECTS.SYSID AS SYSID, 
    QVOBJECTS.DESCRIPTION AS DESCRIPTION,
    QVOBJECTS.REGISTRY AS REGISTRY,
    QVOBJECTS.BEGINTIME AS BEGINTIME,
    QVOBJECTS.ENDTIME AS ENDTIME,
    QVOBJECTS.REFERENCE AS REFERENCE,
    QVOBJECTS.TAG AS TAG,
    QVOBJECTS.TYPOLOGYID AS TYPOLOGYID,
    OBJECTS_ATTORI.EMAIL AS EMAIL,
    OBJECTS_ATTORI.AZIENDAID AS AZIENDAID,
    OBJECTS_ATTORI.PROPRIETAID AS PROPRIETAID,
    OBJECTS_ATTORI.UFFICIOID AS UFFICIOID,
    OBJECTS_ATTORI.PERSONAID AS PERSONAID,
    OBJECTS_ATTORI.UTENTEID AS UTENTEID,
    OBJECTS_ATTORI.RUOLOID AS RUOLOID
FROM QVOBJECTS
INNER JOIN OBJECTS_ATTORI ON OBJECTS_ATTORI.SYSID=QVOBJECTS.SYSID
WHERE
    QVOBJECTS.TYPOLOGYID=[:SYSID(0ATTORI00000)] AND QVOBJECTS.DELETED=0
