CREATE VIEW QW_ATTORIEGO AS
SELECT 
    QW_ATTORI.SYSID AS SYSID, 
    QW_ATTORI.DESCRIPTION AS DESCRIPTION, 
    QW_ATTORI.UFFICIOID AS UFFICIOID, 
    QVUSERS.EGOID AS EGOUTENTEID,
    QVUSERS.ADMINISTRATOR AS EGOADMIN,
    QVUSERS.EMAIL AS EGOEMAIL,
    QVROLES.EGOID AS EGORUOLOID
FROM QW_ATTORI
LEFT JOIN QVUSERS ON QVUSERS.SYSID=QW_ATTORI.UTENTEID
LEFT JOIN QVROLES ON QVROLES.SYSID=QW_ATTORI.RUOLOID
