CREATE VIEW QW_ATTIVITAPRATICA AS
SELECT
    QVARROWS.SYSID AS SYSID, 
    QVARROWS.DESCRIPTION AS DESCRIPTION,
    QVARROWS.REGISTRY AS REGISTRY,
    QVARROWS.TYPOLOGYID AS TYPOLOGYID,
    QVARROWS.AUXTIME AS AUXTIME,
    QVARROWS.BOWTIME AS BOWTIME,
    QVARROWS.BOWID AS BOWID,
    QVARROWS.TARGETTIME AS TARGETTIME,
    QVARROWS.TARGETID AS TARGETID,
    QVARROWS.GENREID AS GENREID,
    QVARROWS.AMOUNT AS AMOUNT,
    QVARROWS.MOTIVEID AS MOTIVEID,
    QVARROWS.REFARROWID AS REFARROWID,
    ARROWS_ATTIVITA.IMPORTANZA AS IMPORTANZA,
    ARROWS_ATTIVITA.PERCENTUALE AS PERCENTUALE,
    ARROWS_ATTIVITA.STATOID AS STATOID,
    QVARROWS.SCOPE AS SCOPE,
    QVARROWS.STATUS AS STATUS,
    QVARROWS.UPDATING AS UPDATING,
    QVARROWS.CONSISTENCY AS CONSISTENCY,
    QVARROWS.AVAILABILITY AS AVAILABILITY,
    QVARROWS.REFERENCE AS REFERENCE,
    QVARROWS.TAG AS TAG,
    QVARROWS.TIMEINSERT AS TIMEINSERT,
    ATTORIBOW.DESCRIPTION AS BOW,
    ATTORITARGET.DESCRIPTION AS TARGET,
    ATTORITARGET.EGOUTENTEID AS TARGETUTENTEEGO,
    ATTORITARGET.EGORUOLOID AS TARGETRUOLOEGO,
    QVQUIVERS.SYSID AS PRATICAID,
    QVQUIVERS.STATUS AS PRATICASTATUS
FROM QVARROWS
INNER JOIN ARROWS_ATTIVITA ON ARROWS_ATTIVITA.SYSID=QVARROWS.SYSID
LEFT JOIN QVOBJECTS ATTORIBOW ON ATTORIBOW.SYSID=QVARROWS.BOWID
LEFT JOIN QW_ATTORIEGO ATTORITARGET ON ATTORITARGET.SYSID=QVARROWS.TARGETID
INNER JOIN QVQUIVERARROW ON QVQUIVERARROW.ARROWID=QVARROWS.SYSID
INNER JOIN QVQUIVERS ON QVQUIVERS.SYSID=QVQUIVERARROW.QUIVERID
WHERE 
    QVARROWS.TYPOLOGYID=[:SYSID(0ATTIVITA000)] AND QVARROWS.DELETED=0
