CREATE VIEW QW_ATTIVITA AS
SELECT 
    QVARROWS.SYSID AS SYSID, 
    QVARROWS.DESCRIPTION AS DESCRIPTION,
    QVARROWS.REGISTRY AS REGISTRY,
    QVARROWS.TYPOLOGYID AS TYPOLOGYID,
    QVARROWS.BOWID AS BOWID,
    QVARROWS.TARGETID AS TARGETID,
    QVARROWS.AUXTIME AS AUXTIME,
    QVARROWS.BOWTIME AS BOWTIME,
    QVARROWS.TARGETTIME AS TARGETTIME,
    QVARROWS.MOTIVEID AS MOTIVEID,
    QVARROWS.GENREID AS GENREID,
    QVARROWS.AMOUNT AS AMOUNT,
    QVARROWS.STATUS AS STATUS,
    QVARROWS.CONSISTENCY AS CONSISTENCY,
    QVARROWS.AVAILABILITY AS AVAILABILITY,
    QVARROWS.PHASE AS PHASE,
    QVARROWS.REFERENCE AS REFERENCE,
    QVARROWS.TAG AS TAG,
    QVARROWS.TIMEINSERT AS TIMEINSERT,
    ARROWS_ATTIVITA.IMPORTANZA AS IMPORTANZA,
    ARROWS_ATTIVITA.PERCENTUALE AS PERCENTUALE,
    ARROWS_ATTIVITA.STATOID AS STATOID,
    ARROWS_ATTIVITA.TRANSID AS TRANSID
FROM QVARROWS
INNER JOIN ARROWS_ATTIVITA ON ARROWS_ATTIVITA.SYSID=QVARROWS.SYSID
WHERE
    QVARROWS.TYPOLOGYID=[:SYSID(0ATTIVITA000)] AND QVARROWS.DELETED=0
