CREATE VIEW QW_CORSI AS
SELECT 
    QVOBJECTS.SYSID AS SYSID, 
    QVOBJECTS.DESCRIPTION AS DESCRIPTION,
    QVOBJECTS.REGISTRY AS REGISTRY,
    QVOBJECTS.REFERENCE AS REFERENCE,
    QVOBJECTS.TAG AS TAG,
    QVOBJECTS.TYPOLOGYID AS TYPOLOGYID,
    QVOBJECTS.BEGINTIME AS BEGINTIME,
    QVOBJECTS.ENDTIME AS ENDTIME,
    QVOBJECTS.AUXAMOUNT AS AUXAMOUNT,
    OBJECTS_CORSI.AZIENDAID AS AZIENDAID,
    OBJECTS_CORSI.LUOGO AS LUOGO,
    OBJECTS_CORSI.TIPOCORSO AS TIPOCORSO,
    OBJECTS_CORSI.REFERENTE AS REFERENTE,
    OBJECTS_CORSI.MOREDATA AS MOREDATA
FROM QVOBJECTS 
LEFT JOIN OBJECTS_CORSI ON OBJECTS_CORSI.SYSID=QVOBJECTS.SYSID 
WHERE 
    QVOBJECTS.TYPOLOGYID=[:SYSID(0CORSIFORMAT)] AND QVOBJECTS.DELETED=0
