CREATE VIEW QW_FINGROUP AS 
SELECT 
    MIN(CASE 
    WHEN CAPID<>'' THEN CAPID
    WHEN INTID<>'' THEN INTID
    WHEN COMMID<>'' THEN COMMID
    WHEN TASSOID<>'' THEN TASSOID
    WHEN SPREADID<>'' THEN SPREADID
    ELSE PRATICAID
    END) AS SYSID,
    PRATICAID, 
    DATAVAL, 
    SUM(CAPITALE) AS CAPITALE, 
    SUM(INTINC) AS INTINC, 
    SUM(INTPAG) AS INTPAG, 
    SUM(TASSOINC+SPREADINC) AS TASSOINC, 
    SUM(TASSOPAG+SPREADPAG) AS TASSOPAG 
FROM QW_FINFLUSSI
GROUP BY PRATICAID,DATAVAL