CREATE VIEW QW_FINFLUSSI AS 
SELECT 
    QW_MOVIMENTI.SYSID AS CAPID,
    ''    AS INTID,
    ''    AS COMMID,
    ''    AS TASSOID,
    ''    AS SPREADID,
    QW_MOVIMENTI.AUXTIME AS DATAVAL,
    -QW_MOVIMENTI.AMOUNT AS CAPITALE,
    0 AS INTINC, 
    0 AS INTPAG, 
    0 AS COMMINC, 
    0 AS COMMPAG, 
    0 AS TASSOINC,
    0 AS TASSOPAG,
    0 AS SPREADINC,
    0 AS SPREADPAG,
    QVQUIVERARROW.QUIVERID AS PRATICAID 
FROM QW_MOVIMENTI 
INNER JOIN QVQUIVERARROW ON QVQUIVERARROW.ARROWID=QW_MOVIMENTI.SYSID
WHERE QW_MOVIMENTI.MOTIVEID=[:SYSID(0CAUSCAPPAG0)]

UNION 

SELECT 
    QW_MOVIMENTI.SYSID AS CAPID,
    ''    AS INTID,
    ''    AS COMMID,
    ''    AS TASSOID,
    ''    AS SPREADID,
    QW_MOVIMENTI.AUXTIME AS DATAVAL,
    QW_MOVIMENTI.AMOUNT AS CAPITALE, 
    0 AS INTINC, 
    0 AS INTPAG, 
    0 AS COMMINC, 
    0 AS COMMPAG, 
    0 AS TASSOINC, 
    0 AS TASSOPAG, 
    0 AS SPREADINC,
    0 AS SPREADPAG,
    QVQUIVERARROW.QUIVERID AS PRATICAID 
FROM QW_MOVIMENTI 
INNER JOIN QVQUIVERARROW ON QVQUIVERARROW.ARROWID=QW_MOVIMENTI.SYSID
WHERE QW_MOVIMENTI.MOTIVEID=[:SYSID(0CAUSCAPINC0)]

UNION 

SELECT 
    ''    AS CAPID,
    QW_MOVIMENTI.SYSID AS INTID,
    ''    AS COMMID,
    ''    AS TASSOID,
    ''    AS SPREADID,
    QW_MOVIMENTI.AUXTIME AS DATAVAL,
    0 AS CAPITALE, 
    QW_MOVIMENTI.AMOUNT AS INTINC, 
    0 AS INTPAG, 
    0 AS COMMINC, 
    0 AS COMMPAG, 
    0 AS TASSOINC, 
    0 AS TASSOPAG, 
    0 AS SPREADINC,
    0 AS SPREADPAG,
    QVQUIVERARROW.QUIVERID AS PRATICAID 
FROM QW_MOVIMENTI 
INNER JOIN QVQUIVERARROW ON QVQUIVERARROW.ARROWID=QW_MOVIMENTI.SYSID
WHERE QW_MOVIMENTI.MOTIVEID=[:SYSID(0CAUSINTINC0)]

UNION 

SELECT 
    ''    AS CAPID,
    QW_MOVIMENTI.SYSID AS INTID,
    ''    AS COMMID,
    ''    AS TASSOID,
    ''    AS SPREADID,
    QW_MOVIMENTI.AUXTIME AS DATAVAL,
    0 AS CAPITALE, 
    0 AS INTINC, 
    QW_MOVIMENTI.AMOUNT AS INTPAG, 
    0 AS COMMINC, 
    0 AS COMMPAG, 
    0 AS TASSOINC, 
    0 AS TASSOPAG, 
    0 AS SPREADINC,
    0 AS SPREADPAG,
    QVQUIVERARROW.QUIVERID AS PRATICAID 
FROM QW_MOVIMENTI 
INNER JOIN QVQUIVERARROW ON QVQUIVERARROW.ARROWID=QW_MOVIMENTI.SYSID
WHERE QW_MOVIMENTI.MOTIVEID=[:SYSID(0CAUSINTPAG0)]

UNION 

SELECT 
    ''    AS CAPID,
    ''    AS INTID,
    QW_MOVIMENTI.SYSID AS COMMID,
    ''    AS TASSOID,
    ''    AS SPREADID,
    QW_MOVIMENTI.AUXTIME AS DATAVAL,
    0 AS CAPITALE, 
    0 AS INTINC, 
    0 AS INTPAG, 
    QW_MOVIMENTI.AMOUNT AS COMMINC, 
    0 AS COMMPAG, 
    0 AS TASSOINC, 
    0 AS TASSOPAG, 
    0 AS SPREADINC,
    0 AS SPREADPAG,
    QVQUIVERARROW.QUIVERID AS PRATICAID 
FROM QW_MOVIMENTI 
INNER JOIN QVQUIVERARROW ON QVQUIVERARROW.ARROWID=QW_MOVIMENTI.SYSID
WHERE QW_MOVIMENTI.MOTIVEID=[:SYSID(0CAUSCOMMINC)]

UNION 

SELECT 
    ''    AS CAPID,
    ''    AS INTID,
    QW_MOVIMENTI.SYSID AS COMMID,
    ''    AS TASSOID,
    ''    AS SPREADID,
    QW_MOVIMENTI.AUXTIME AS DATAVAL,
    0 AS CAPITALE, 
    0 AS INTINC, 
    0 AS INTPAG, 
    0 AS COMMINC, 
    QW_MOVIMENTI.AMOUNT AS COMMPAG, 
    0 AS TASSOINC, 
    0 AS TASSOPAG, 
    0 AS SPREADINC,
    0 AS SPREADPAG,
    QVQUIVERARROW.QUIVERID AS PRATICAID 
FROM QW_MOVIMENTI 
INNER JOIN QVQUIVERARROW ON QVQUIVERARROW.ARROWID=QW_MOVIMENTI.SYSID
WHERE QW_MOVIMENTI.MOTIVEID=[:SYSID(0CAUSCOMMPAG)]

UNION 

SELECT 
    ''    AS CAPID,
    ''    AS INTID,
    ''    AS COMMID,
    QW_FINEVENTI.SYSID AS TASSOID,
    ''    AS SPREADID,
    QW_FINEVENTI.AUXTIME AS DATAVAL,
    0 AS CAPITALE, 
    0 AS INTINC, 
    0 AS INTPAG, 
    0 AS COMMINC, 
    0 AS COMMPAG, 
    QW_FINEVENTI.AMOUNT AS TASSOINC, 
    0 AS TASSOPAG, 
    0 AS SPREADINC,
    0 AS SPREADPAG,
    QVQUIVERARROW.QUIVERID AS PRATICAID 
FROM QW_FINEVENTI 
INNER JOIN QVQUIVERARROW ON QVQUIVERARROW.ARROWID=QW_FINEVENTI.SYSID
WHERE QW_FINEVENTI.GENREID=[:SYSID(0TASSOANNUO0)] AND QW_FINEVENTI.TARGETID<>''

UNION 

SELECT 
    ''    AS CAPID,
    ''    AS INTID,
    ''    AS COMMID,
    QW_FINEVENTI.SYSID AS TASSOID,
    ''    AS SPREADID,
    QW_FINEVENTI.AUXTIME AS DATAVAL,  
    0 AS CAPITALE, 
    0 AS INTINC, 
    0 AS INTPAG, 
    0 AS COMMINC, 
    0 AS COMMPAG, 
    0 AS TASSOINC, 
    QW_FINEVENTI.AMOUNT AS TASSOPAG, 
    0 AS SPREADINC,
    0 AS SPREADPAG,
    QVQUIVERARROW.QUIVERID AS PRATICAID 
FROM QW_FINEVENTI 
INNER JOIN QVQUIVERARROW ON QVQUIVERARROW.ARROWID=QW_FINEVENTI.SYSID
WHERE QW_FINEVENTI.GENREID=[:SYSID(0TASSOANNUO0)] AND QW_FINEVENTI.BOWID<>''

UNION 

SELECT 
    ''    AS CAPID,
    ''    AS INTID,
    ''    AS COMMID,
    ''    AS TASSOID,
    QW_FINEVENTI.SYSID AS SPREADID,
    QW_FINEVENTI.AUXTIME AS DATAVAL,
    0 AS CAPITALE, 
    0 AS INTINC, 
    0 AS INTPAG, 
    0 AS COMMINC, 
    0 AS COMMPAG, 
    0 AS TASSOINC, 
    0 AS TASSOPAG, 
    QW_FINEVENTI.AMOUNT AS SPREADINC,
    0 AS SPREADPAG,
    QVQUIVERARROW.QUIVERID AS PRATICAID 
FROM QW_FINEVENTI 
INNER JOIN QVQUIVERARROW ON QVQUIVERARROW.ARROWID=QW_FINEVENTI.SYSID
WHERE QW_FINEVENTI.GENREID=[:SYSID(0SPREADANNUO)] AND QW_FINEVENTI.TARGETID<>''

UNION 

SELECT 
    ''    AS CAPID,
    ''    AS INTID,
    ''    AS COMMID,
    ''    AS TASSOID,
    QW_FINEVENTI.SYSID AS SPREADID,
    QW_FINEVENTI.AUXTIME AS DATAVAL,  
    0 AS CAPITALE, 
    0 AS INTINC, 
    0 AS INTPAG, 
    0 AS COMMINC, 
    0 AS COMMPAG, 
    0 AS TASSOINC, 
    0 AS TASSOPAG, 
    0 AS SPREADINC,
    QW_FINEVENTI.AMOUNT AS SPREADPAG,
    QVQUIVERARROW.QUIVERID AS PRATICAID 
FROM QW_FINEVENTI 
INNER JOIN QVQUIVERARROW ON QVQUIVERARROW.ARROWID=QW_FINEVENTI.SYSID
WHERE QW_FINEVENTI.GENREID=[:SYSID(0SPREADANNUO)] AND QW_FINEVENTI.BOWID<>''
