CREATE VIEW QW_FINEVENTI AS 
SELECT 
    QVARROWS.SYSID AS SYSID,
    QVARROWS.DESCRIPTION AS DESCRIPTION,
    QVARROWS.REGISTRY AS REGISTRY,
    QVARROWS.TYPOLOGYID AS TYPOLOGYID,
    QVARROWS.BOWID AS BOWID,
    QVARROWS.TARGETID AS TARGETID,
    QVARROWS.BOWTIME AS BOWTIME,
    QVARROWS.TARGETTIME AS TARGETTIME,
    QVARROWS.AUXTIME AS AUXTIME,
    QVARROWS.AMOUNT AS AMOUNT,
    QVARROWS.TAG AS TAG,
    QVARROWS.STATUS AS STATUS,
    QVARROWS.PHASE AS PHASE,
    QVARROWS.CONSISTENCY AS CONSISTENCY,
    QVARROWS.MOTIVEID AS MOTIVEID,
    QVARROWS.GENREID AS GENREID,
    ARROWS_FINEVENTI.SCAGLIONE AS SCAGLIONE,
    ARROWS_FINEVENTI.DIVIDENDO AS DIVIDENDO,
    ARROWS_FINEVENTI.DIVISORE AS DIVISORE
FROM QVARROWS 
INNER JOIN ARROWS_FINEVENTI ON ARROWS_FINEVENTI.SYSID=QVARROWS.SYSID 
WHERE 
    QVARROWS.TYPOLOGYID=[:SYSID(0FINEVENTI00)] AND QVARROWS.DELETED=0
