CREATE VIEW QW_FLUSSI AS 
SELECT 
    QVARROWS.SYSID AS SYSID,
    QVARROWS.DESCRIPTION AS DESCRIPTION,
    QVARROWS.REGISTRY AS REGISTRY,
    QVARROWS.TYPOLOGYID AS TYPOLOGYID,
    QVARROWS.BOWID AS BOWID,
    QVARROWS.TARGETID AS TARGETID,
    QVARROWS.BOWTIME AS BOWTIME,
    QVARROWS.TARGETTIME AS TARGETTIME,
    QVARROWS.AUXTIME AS AUXTIME,
    QVARROWS.AMOUNT AS AMOUNT,
    QVARROWS.TAG AS TAG,
    QVARROWS.STATUS AS STATUS,
    QVARROWS.PHASE AS PHASE,
    QVARROWS.CONSISTENCY AS CONSISTENCY,
    QVARROWS.MOTIVEID AS MOTIVEID,
    QVARROWS.GENREID AS GENREID,
    QVARROWS.REFARROWID AS REFARROWID,
    ARROWS_FLUSSI.ALIQUOTA AS ALIQUOTA
FROM QVARROWS 
INNER JOIN ARROWS_FLUSSI ON ARROWS_FLUSSI.SYSID=QVARROWS.SYSID 
WHERE 
    QVARROWS.TYPOLOGYID=[:SYSID(0FLUSSI00000)] AND QVARROWS.DELETED=0
