CREATE VIEW QW_FLUSSIJOIN AS
SELECT 
    QW_FLUSSI.SYSID AS SYSID, 
    QW_FLUSSI.DESCRIPTION AS DESCRIPTION,
    QW_FLUSSI.REGISTRY AS REGISTRY,
    QW_FLUSSI.TYPOLOGYID AS TYPOLOGYID,
    QW_FLUSSI.BOWID AS BOWID,
    QW_FLUSSI.TARGETID AS TARGETID,
    QW_FLUSSI.BOWTIME AS BOWTIME,
    QW_FLUSSI.TARGETTIME AS TARGETTIME,
    QW_FLUSSI.AUXTIME AS AUXTIME,
    QW_FLUSSI.AMOUNT AS AMOUNT,
    QW_FLUSSI.TAG AS TAG,
    QW_FLUSSI.STATUS AS STATUS,
    QW_FLUSSI.PHASE AS PHASE,
    QW_FLUSSI.CONSISTENCY AS CONSISTENCY,
    QW_FLUSSI.MOTIVEID AS MOTIVEID,
    QVMOTIVES.DESCRIPTION AS MOTIVE,
    QW_FLUSSI.GENREID AS GENREID,
    QW_FLUSSI.ALIQUOTA AS ALIQUOTA,
    QVGENRES.DESCRIPTION AS GENRE,
    CASE 
    WHEN QVARROWS.SYSID IS NULL THEN 1
    ELSE QVARROWS.AMOUNT
    END AS STUFFAMOUNT
FROM QW_FLUSSI
INNER JOIN QVMOTIVES ON QVMOTIVES.SYSID=QW_FLUSSI.MOTIVEID
INNER JOIN QVGENRES ON QVGENRES.SYSID=QW_FLUSSI.GENREID
LEFT JOIN QVARROWS ON QVARROWS.SYSID=QW_FLUSSI.REFARROWID
