CREATE VIEW QW_LISTINIJOIN AS
SELECT
    QVEQUIVALENCES.SYSID AS SYSID, 
    EQARROWS.DESCRIPTION AS DESCRIPTION,
    EQARROWS.TAG AS TAG,
    EQARROWS.AUXTIME AS AUXTIME,
    REALARROWS.TYPOLOGYID AS REFTYPOLOGYID,
    REALARROWS.GENREID AS REFGENREID,
    REALARROWS.MOTIVEID AS REFMOTIVEID,
    REALARROWS.AMOUNT AS REFAMOUNT,
    REALGENRES.DESCRIPTION AS REFGENRE,
    EQARROWS.TYPOLOGYID AS EQTYPOLOGYID,
    EQARROWS.GENREID AS EQGENREID,
    EQARROWS.MOTIVEID AS EQMOTIVEID,
    EQARROWS.AMOUNT AS EQAMOUNT,
    EQGENRES.DESCRIPTION AS EQGENRE,
    QVQUIVERARROW.QUIVERID AS LISTINOID
FROM QVEQUIVALENCES
INNER JOIN QVARROWS REALARROWS ON REALARROWS.SYSID=QVEQUIVALENCES.REFERENCEID
INNER JOIN QVGENRES REALGENRES ON REALGENRES.SYSID=REALARROWS.GENREID
INNER JOIN QVARROWS EQARROWS ON EQARROWS.SYSID=QVEQUIVALENCES.EQUIVALENTID
INNER JOIN QVGENRES EQGENRES ON EQGENRES.SYSID=EQARROWS.GENREID
INNER JOIN QVQUIVERARROW ON QVQUIVERARROW.ARROWID=REALARROWS.SYSID
