CREATE VIEW QW_MOTIVISTATO AS
SELECT 
    QVMOTIVES.SYSID AS SYSID, 
    QVMOTIVES.DESCRIPTION AS DESCRIPTION,
    QVMOTIVES.REGISTRY AS REGISTRY,
    QVMOTIVES.COUNTERPARTID AS COUNTERPARTID,
    MOTIVES_ATTIVITA.ORDINATORE AS ORDINATORE,
    MOTIVES_ATTIVITA.RIFERIMENTOINIZIO AS RIFERIMENTOINIZIO,
    MOTIVES_ATTIVITA.RIFERIMENTOFINE AS RIFERIMENTOFINE,
    MOTIVES_ATTIVITA.MESEINIZIO AS MESEINIZIO,
    MOTIVES_ATTIVITA.MESEFINE AS MESEFINE,
    MOTIVES_ATTIVITA.GIORNOINIZIO AS GIORNOINIZIO,
    MOTIVES_ATTIVITA.GIORNOFINE AS GIORNOFINE,
    MOTIVES_ATTIVITA.ORAINIZIO AS ORAINIZIO,
    MOTIVES_ATTIVITA.ORAFINE AS ORAFINE,
    MOTIVES_ATTIVITA.CALCOLO AS CALCOLO,
    MOTIVES_ATTIVITA.PREAVVISO AS PREAVVISO,
    MOTIVES_ATTIVITA.INTESTAZIONE AS INTESTAZIONE,
    QVSELECTIONS.PARENTID AS STATOID,
    QVSELECTIONS.ENABLED AS ENABLED,
    QVSELECTIONS.FLAG1 AS AUTOMATICA,
    QVSELECTIONS.FLAG2 AS INIZIATA,
    QVSELECTIONS.FLAG3 AS TERMINATA
FROM QVMOTIVES
INNER JOIN QVSELECTIONS ON QVSELECTIONS.SELECTEDID=QVMOTIVES.SYSID
INNER JOIN MOTIVES_ATTIVITA ON MOTIVES_ATTIVITA.SYSID=QVMOTIVES.SYSID
WHERE DELETED=0
