CREATE VIEW QW_MOTIVIATTIVITA AS
SELECT 
    QVMOTIVES.SYSID AS SYSID, 
    QVMOTIVES.NAME AS NAME,
    QVMOTIVES.DESCRIPTION AS DESCRIPTION,
    QVMOTIVES.REGISTRY AS REGISTRY,
    QVMOTIVES.TYPOLOGYID AS TYPOLOGYID,
    QVMOTIVES.DIRECTION AS DIRECTION,
    QVMOTIVES.REFERENCEID AS REFERENCEID,
    QVMOTIVES.COUNTERPARTID AS COUNTERPARTID,
    QVMOTIVES.TAG AS TAG,
    MOTIVES_ATTIVITA.GANTT AS GANTT,
    MOTIVES_ATTIVITA.INVIOEMAIL AS INVIOEMAIL,
    MOTIVES_ATTIVITA.SETCONOSCENZA AS SETCONOSCENZA,
    MOTIVES_ATTIVITA.PROCESSOID AS PROCESSOID
FROM QVMOTIVES
INNER JOIN MOTIVES_ATTIVITA ON MOTIVES_ATTIVITA.SYSID=QVMOTIVES.SYSID
WHERE
    QVMOTIVES.TYPOLOGYID=[:SYSID(0MOTIVIATTIV)] AND DELETED=0
