CREATE VIEW QW_PROCCOINVOLTI AS
SELECT 
    QW_ATTORIJOIN.SYSID AS SYSID, 
    QW_ATTORIJOIN.DESCRIPTION AS DESCRIPTION,
    QW_ATTORIJOIN.EGOUTENTEID AS EGOUTENTEID,
    QW_ATTORIJOIN.EGORUOLOID AS EGORUOLOID,
    QW_PROCESSI.SYSID AS PROCESSOID,
    QVSELECTIONS.SYSID AS SELECTIONID
FROM QVSELECTIONS
INNER JOIN QW_PROCESSI ON QW_PROCESSI.SYSID=QVSELECTIONS.PARENTID
INNER JOIN QW_ATTORIJOIN ON QW_ATTORIJOIN.SYSID=QVSELECTIONS.SELECTEDID

