CREATE VIEW QW_PROCESSIJOIN AS
SELECT DISTINCT
    QVQUIVERS.SYSID AS SYSID, 
    QVQUIVERS.DESCRIPTION AS DESCRIPTION,
    QVQUIVERS.TYPOLOGYID AS TYPOLOGYID,
    QUIVERS_PROCESSI.SETINTERPROCESSO AS SETINTERPROCESSO,
    QUIVERS_PROCESSI.DATIAGGIUNTIVI AS DATIAGGIUNTIVI,
    QVUSERS.EGOID AS EGOUTENTEID
FROM QVQUIVERS
INNER JOIN QUIVERS_PROCESSI ON QUIVERS_PROCESSI.SYSID=QVQUIVERS.SYSID
INNER JOIN QW_PROCSTATI ON QW_PROCSTATI.PROCESSOID=QVQUIVERS.SYSID
INNER JOIN QW_ATTORI ON QW_ATTORI.SYSID=QW_PROCSTATI.ATTOREID
INNER JOIN QVUSERS ON QVUSERS.SYSID=QW_ATTORI.UTENTEID
WHERE
    QVQUIVERS.TYPOLOGYID=[:SYSID(0PROCESSI000)] AND QVQUIVERS.DELETED=0 AND
    QW_PROCSTATI.INIZIALE=1
