CREATE VIEW QW_PROCESSI AS
SELECT 
    QVQUIVERS.SYSID AS SYSID, 
    QVQUIVERS.DESCRIPTION AS DESCRIPTION,
    QVQUIVERS.TYPOLOGYID AS TYPOLOGYID
FROM QVQUIVERS
INNER JOIN QUIVERS_PROCESSI ON QUIVERS_PROCESSI.SYSID=QVQUIVERS.SYSID
WHERE
    QVQUIVERS.TYPOLOGYID=[:SYSID(0PROCESSI000)] AND QVQUIVERS.DELETED=0
