CREATE VIEW QW_PRATICHEJOIN AS
SELECT 
    QW_PRATICHE.SYSID AS SYSID, 
    QW_PRATICHE.DESCRIPTION AS DESCRIPTION,
    QW_PRATICHE.REGISTRY AS REGISTRY,
    QW_PRATICHE.TYPOLOGYID AS TYPOLOGYID,
    QW_PRATICHE.PROCESSOID AS PROCESSOID,
    QW_PRATICHE.STATOID AS STATOID,
    QW_PRATICHE.RICHIEDENTEID AS RICHIEDENTEID,
    QW_PRATICHE.MEDIATOREID AS MEDIATOREID,
    QW_PRATICHE.CONTOID AS CONTOID,
    QW_PRATICHE.MAGAZZINOID AS MAGAZZINOID,
    QW_PRATICHE.AUXTIME AS AUXTIME,
    QW_PRATICHE.AUXAMOUNT AS AUXAMOUNT,
    QW_PRATICHE.DATAINIZIO AS DATAINIZIO,
    QW_PRATICHE.DATAFINE AS DATAFINE,
    QW_PRATICHE.STATUS AS STATUS,
    QW_PRATICHE.STATUSTIME AS STATUSTIME,
    QW_PRATICHE.CONSISTENCY AS CONSISTENCY,
    QW_PRATICHE.REFERENCE AS REFERENCE,
    QW_PRATICHE.TAG AS TAG,
    QW_PRATICHE.GANTT AS GANTT,
    QW_PRATICHE.INVIOEMAIL AS INVIOEMAIL,
    QW_PRATICHE.TIMEINSERT AS TIMEINSERT,
    QW_PRATICHE.MOREDATA AS MOREDATA,
    QW_PROCSTATI.DESCRIPTION AS STATODESCR,
    QW_PROCSTATI.ATTOREID AS ATTOREID,
    QW_PROCSTATI.CONTOID AS STATOCONTOID,
    QW_PROCSTATI.INIZIALE AS INIZIALE,
    QW_PROCSTATI.FINALE AS FINALE,
    QW_PROCSTATI.ORDINATORE AS ORDINATORE, 
    ATTORI.DESCRIPTION AS ATTORE,
    RICHIEDENTI.DESCRIPTION AS RICHIEDENTE
FROM QW_PRATICHE
LEFT JOIN QW_PROCSTATI ON QW_PROCSTATI.SYSID=QW_PRATICHE.STATOID
LEFT JOIN QW_ATTORI ATTORI ON ATTORI.SYSID=QW_PROCSTATI.ATTOREID
LEFT JOIN QW_ATTORI RICHIEDENTI ON RICHIEDENTI.SYSID=QW_PRATICHE.RICHIEDENTEID
