CREATE VIEW QW_PROCSTATI AS
SELECT 
    QVOBJECTS.SYSID AS SYSID, 
    QVOBJECTS.DESCRIPTION AS DESCRIPTION,
    QVOBJECTS.TAG AS TAG,
    QVOBJECTS.REGISTRY AS REGISTRY,
    QVOBJECTS.TYPOLOGYID AS TYPOLOGYID,
    OBJECTS_PROCSTATI.PROCESSOID AS PROCESSOID,
    OBJECTS_PROCSTATI.ATTOREID AS ATTOREID,
    OBJECTS_PROCSTATI.CONTOID AS CONTOID,
    OBJECTS_PROCSTATI.INIZIALE AS INIZIALE,
    OBJECTS_PROCSTATI.FINALE AS FINALE,
    OBJECTS_PROCSTATI.ORDINATORE AS ORDINATORE
FROM QVOBJECTS
INNER JOIN OBJECTS_PROCSTATI ON OBJECTS_PROCSTATI.SYSID=QVOBJECTS.SYSID
WHERE
    QVOBJECTS.TYPOLOGYID=[:SYSID(0PROCSTATI00)] AND QVOBJECTS.DELETED=0
