CREATE VIEW QW_PROCSTATIJOIN AS
SELECT 
    QW_PROCSTATI.SYSID AS SYSID, 
    QW_PROCSTATI.DESCRIPTION AS DESCRIPTION,
    QW_PROCSTATI.TAG AS TAG,
    QW_PROCSTATI.REGISTRY AS REGISTRY,
    QW_PROCSTATI.TYPOLOGYID AS TYPOLOGYID,
    QW_PROCSTATI.PROCESSOID AS PROCESSOID,
    QW_PROCSTATI.ATTOREID AS ATTOREID,
    QW_PROCSTATI.CONTOID AS CONTOID,
    QW_PROCSTATI.INIZIALE AS INIZIALE,
    QW_PROCSTATI.FINALE AS FINALE,
    QW_PROCSTATI.ORDINATORE AS ORDINATORE, 
    OBJATTORI.DESCRIPTION AS ATTORE,
    OBJCONTI.DESCRIPTION AS CONTO,
    OBJCONTI.REFGENREID AS GENREID
FROM QW_PROCSTATI
LEFT JOIN QVOBJECTS OBJATTORI ON OBJATTORI.SYSID=QW_PROCSTATI.ATTOREID
LEFT JOIN QVOBJECTS OBJCONTI ON OBJCONTI.SYSID=QW_PROCSTATI.CONTOID
