CREATE VIEW QW_PRATICHE AS
SELECT 
    QVQUIVERS.SYSID AS SYSID, 
    QVQUIVERS.DESCRIPTION AS DESCRIPTION,
    QVQUIVERS.REGISTRY AS REGISTRY,
    QVQUIVERS.TYPOLOGYID AS TYPOLOGYID,
    QVQUIVERS.AUXTIME AS AUXTIME,
    QVQUIVERS.AUXAMOUNT AS AUXAMOUNT,
    QVQUIVERS.STATUS AS STATUS,
    QVQUIVERS.STATUSTIME AS STATUSTIME,
    QVQUIVERS.CONSISTENCY AS CONSISTENCY,
    QVQUIVERS.REFERENCE AS REFERENCE,
    QVQUIVERS.TAG AS TAG,
    QVQUIVERS.TIMEINSERT AS TIMEINSERT,
    QVQUIVERS.MOREDATA AS MOREDATA,
    QUIVERS_PRATICHE.DATAINIZIO AS DATAINIZIO,
    QUIVERS_PRATICHE.DATAFINE AS DATAFINE,
    QUIVERS_PRATICHE.PROCESSOID AS PROCESSOID,
    QUIVERS_PRATICHE.STATOID AS STATOID,
    QUIVERS_PRATICHE.RICHIEDENTEID AS RICHIEDENTEID,
    QUIVERS_PRATICHE.MEDIATOREID AS MEDIATOREID,
    QUIVERS_PRATICHE.CONTOID AS CONTOID,
    QUIVERS_PRATICHE.MAGAZZINOID AS MAGAZZINOID,
    QUIVERS_PRATICHE.GANTT AS GANTT,
    QUIVERS_PRATICHE.INVIOEMAIL AS INVIOEMAIL
FROM QVQUIVERS
INNER JOIN QUIVERS_PRATICHE ON QUIVERS_PRATICHE.SYSID=QVQUIVERS.SYSID
WHERE
    QVQUIVERS.TYPOLOGYID=[:SYSID(0PRATICHE000)] AND QVQUIVERS.DELETED=0
