CREATE VIEW QW_TRASFERIMENTIJOIN AS
SELECT 
    QW_TRASFERIMENTI.SYSID AS SYSID, 
    QW_TRASFERIMENTI.DESCRIPTION AS DESCRIPTION,
    QW_TRASFERIMENTI.REGISTRY AS REGISTRY,
    QW_TRASFERIMENTI.TYPOLOGYID AS TYPOLOGYID,
    QW_TRASFERIMENTI.BOWID AS BOWID,
    QW_TRASFERIMENTI.TARGETID AS TARGETID,
    QW_TRASFERIMENTI.BOWTIME AS BOWTIME,
    QW_TRASFERIMENTI.TARGETTIME AS TARGETTIME,
    QW_TRASFERIMENTI.AUXTIME AS AUXTIME,
    QW_TRASFERIMENTI.AMOUNT AS AMOUNT,
    QW_TRASFERIMENTI.TAG AS TAG,
    QW_TRASFERIMENTI.STATUS AS STATUS,
    QW_TRASFERIMENTI.PHASE AS PHASE,
    QW_TRASFERIMENTI.MOTIVEID AS MOTIVEID,
    QW_TRASFERIMENTI.SERVIZIOID AS SERVIZIOID,
    QVMOTIVES.DESCRIPTION AS MOTIVE,
    QW_TRASFERIMENTI.GENREID AS GENREID,
    QW_ARTICOLI.DESCRIPTION AS GENRE,
    QW_ARTICOLI.PROCESSOID AS PROCESSOID
FROM QW_TRASFERIMENTI
INNER JOIN QVMOTIVES ON QVMOTIVES.SYSID=QW_TRASFERIMENTI.MOTIVEID
INNER JOIN QW_ARTICOLI ON QW_ARTICOLI.SYSID=QW_TRASFERIMENTI.GENREID
