CREATE VIEW QW_TRANSIZIONIJOIN AS
SELECT 
    QW_TRANSIZIONI.SYSID AS SYSID, 
    QW_TRANSIZIONI.DESCRIPTION AS DESCRIPTION,
    QW_TRANSIZIONI.REGISTRY AS REGISTRY,
    QW_TRANSIZIONI.TYPOLOGYID AS TYPOLOGYID,
    QW_TRANSIZIONI.BOWID AS BOWID,
    QW_TRANSIZIONI.TARGETID AS TARGETID,
    QW_TRANSIZIONI.TAG AS TAG,
    QW_TRANSIZIONI.SVINCOLANTE AS SVINCOLANTE,
    STATI_BOW.DESCRIPTION AS BOWDESCR,
    STATI_BOW.PROCESSOID AS PROCESSOID,
    STATI_BOW.ATTOREID AS ATTOREBOWID,
    STATI_TARGET.DESCRIPTION AS TARGETDESCR,
    STATI_TARGET.ATTOREID AS ATTORETARGETID,
    ATTORI_BOW.DESCRIPTION AS ATTOREBOW,
    ATTORI_TARGET.DESCRIPTION AS ATTORETARGET
FROM QW_TRANSIZIONI
LEFT JOIN QW_PROCSTATI STATI_BOW ON STATI_BOW.SYSID=QW_TRANSIZIONI.BOWID
LEFT JOIN QW_PROCSTATI STATI_TARGET ON STATI_TARGET.SYSID=QW_TRANSIZIONI.TARGETID
LEFT JOIN QW_ATTORI ATTORI_BOW ON ATTORI_BOW.SYSID=STATI_BOW.ATTOREID
LEFT JOIN QW_ATTORI ATTORI_TARGET ON ATTORI_TARGET.SYSID=STATI_TARGET.ATTOREID
