CREATE VIEW QW_TRASFERIMENTI AS 
SELECT 
    QVARROWS.SYSID AS SYSID,
    QVARROWS.DESCRIPTION AS DESCRIPTION,
    QVARROWS.REGISTRY AS REGISTRY,
    QVARROWS.TYPOLOGYID AS TYPOLOGYID,
    QVARROWS.BOWID AS BOWID,
    QVARROWS.TARGETID AS TARGETID,
    QVARROWS.BOWTIME AS BOWTIME,
    QVARROWS.TARGETTIME AS TARGETTIME,
    QVARROWS.AUXTIME AS AUXTIME,
    QVARROWS.AMOUNT AS AMOUNT,
    QVARROWS.TAG AS TAG,
    QVARROWS.STATUS AS STATUS,
    QVARROWS.PHASE AS PHASE,
    QVARROWS.MOTIVEID AS MOTIVEID,
    QVARROWS.GENREID AS GENREID
FROM QVARROWS 
INNER JOIN ARROWS_TRASFERIMENTI ON ARROWS_TRASFERIMENTI.SYSID=QVARROWS.SYSID 
WHERE 
    QVARROWS.TYPOLOGYID=[:SYSID(0TRASFERIMEN)] AND QVARROWS.DELETED=0
