CREATE VIEW QW_TRANSIZIONI AS
SELECT 
    QVARROWS.SYSID AS SYSID, 
    QVARROWS.DESCRIPTION AS DESCRIPTION,
    QVARROWS.REGISTRY AS REGISTRY,
    QVARROWS.TYPOLOGYID AS TYPOLOGYID,
    QVARROWS.BOWID AS BOWID,
    QVARROWS.TARGETID AS TARGETID,
    QVARROWS.TAG AS TAG,
    ARROWS_TRANSIZIONI.SVINCOLANTE AS SVINCOLANTE
FROM QVARROWS
INNER JOIN ARROWS_TRANSIZIONI ON ARROWS_TRANSIZIONI.SYSID=QVARROWS.SYSID
WHERE
    QVARROWS.TYPOLOGYID=[:SYSID(0TRANSIZIONI)] AND QVARROWS.DELETED=0
