CREATE VIEW QW_WEBCONTAINERS AS 
SELECT 
    QVOBJECTS.SYSID AS SYSID,
    QVOBJECTS.DESCRIPTION AS DESCRIPTION,
    QVOBJECTS.TAG AS TAG,
    OBJECTS_WEBCONTAINERS.SITEID AS SITEID,
    OBJECTS_WEBCONTAINERS.CONTENTID AS CONTENTID,
    OBJECTS_WEBCONTAINERS.ORDINATORE AS ORDINATORE
FROM QVOBJECTS
INNER JOIN OBJECTS_WEBCONTAINERS ON OBJECTS_WEBCONTAINERS.SYSID=QVOBJECTS.SYSID 
WHERE 
    QVOBJECTS.TYPOLOGYID=[:SYSID(0WEBCONTAIN0)]
