CREATE VIEW QW_WEBCONTENTSJOIN AS 
SELECT DISTINCT
    QW_WEBCONTENTS.SYSID AS SYSID,
    QW_WEBCONTENTS.DESCRIPTION AS DESCRIPTION,
    QW_WEBCONTENTS.SCOPE AS SCOPE,
    QW_WEBCONTENTS.TARGETTIME AS TARGETTIME,
    QW_WEBCONTENTS.SITEID AS SITEID,
    QW_WEBCONTENTS.SETRELATED AS SETRELATED,
    QVOBJECTS.DESCRIPTION AS SITE,
    QVSELECTIONS.PARENTID AS PARENTID,
    QVSELECTIONS.SORTER AS SORTER
FROM QW_WEBCONTENTS
LEFT JOIN QVOBJECTS ON QVOBJECTS.SYSID=QW_WEBCONTENTS.SITEID 
LEFT JOIN QVSELECTIONS ON QVSELECTIONS.SELECTEDID=QW_WEBCONTENTS.SYSID 
