CREATE VIEW QW_WEBCONTAINERSJOIN AS 
SELECT 
    QW_WEBCONTAINERS.SYSID AS SYSID,
    QW_WEBCONTAINERS.DESCRIPTION AS DESCRIPTION,
    QW_WEBCONTAINERS.TAG AS TAG,
    QW_WEBCONTAINERS.SITEID AS SITEID,
    QW_WEBCONTAINERS.CONTENTID AS CONTENTID,
    QW_WEBCONTAINERS.ORDINATORE AS ORDINATORE,
    QW_WEBCONTENTS.DESCRIPTION AS CONTENT,
    QVSELECTIONS.PARENTID AS PARENTID,
    QVSELECTIONS.SORTER AS SORTER
FROM QW_WEBCONTAINERS
LEFT JOIN QW_WEBCONTENTS ON QW_WEBCONTENTS.SYSID=QW_WEBCONTAINERS.CONTENTID 
LEFT JOIN QVSELECTIONS ON QVSELECTIONS.SELECTEDID=QW_WEBCONTAINERS.SYSID 
