CREATE VIEW QW_WEBCONTENTS AS 
SELECT 
    QVARROWS.SYSID AS SYSID,
    QVARROWS.DESCRIPTION AS DESCRIPTION,
    QVARROWS.SCOPE AS SCOPE,
    QVARROWS.TAG AS TAG,
    QVARROWS.TARGETTIME AS TARGETTIME,
    ARROWS_WEBCONTENTS.SITEID AS SITEID,
    ARROWS_WEBCONTENTS.ABSTRACT AS ABSTRACT,
    ARROWS_WEBCONTENTS.ICON AS ICON,
    ARROWS_WEBCONTENTS.CONTENTTYPE AS CONTENTTYPE,
    ARROWS_WEBCONTENTS.SETRELATED AS SETRELATED
FROM QVARROWS
INNER JOIN ARROWS_WEBCONTENTS ON ARROWS_WEBCONTENTS.SYSID=QVARROWS.SYSID 
WHERE 
    QVARROWS.TYPOLOGYID=[:SYSID(0WEBCONTENTS)] AND QVARROWS.DELETED=0
