CREATE VIEW QWEQUIBROWSER AS
SELECT DISTINCT
    EQUIS.SYSID AS SYSID,
    QVEQUIVALENCES.REFERENCEID AS REFERENCEID, 
    [:BOOL(QVEQUIVALENCES.SYSID IS NOT NULL)] AS EQUIVALENCE, 
    EQUIS.DESCRIPTION AS DESCRIPTION,
    EQUIS.TYPOLOGYID AS TYPOLOGYID,
    EQUIS.AUXTIME AS AUXTIME,
    EQUIS.MOTIVEID AS MOTIVEID,
    EQUIS.GENREID AS GENREID,
    EQUIS.AMOUNT AS AMOUNT,
    EQUIS.TAG AS TAG
FROM QVARROWS EQUIS
LEFT JOIN QVEQUIVALENCES ON QVEQUIVALENCES.EQUIVALENTID=EQUIS.SYSID
WHERE EQUIS.DELETED=0
