CREATE VIEW QWEQUIVALENCES AS
SELECT 
    QVEQUIVALENCES.SYSID AS SYSID, 
    QVEQUIVALENCES.REFERENCEID AS REFERENCEID, 
    QVEQUIVALENCES.EQUIVALENTID AS EQUIVALENTID, 
    REFS.DESCRIPTION AS REFDESCR,
    EQUIS.DESCRIPTION AS EQUIDESCR
FROM QVEQUIVALENCES
INNER JOIN QVARROWS REFS ON REFS.SYSID=QVEQUIVALENCES.REFERENCEID
INNER JOIN QVARROWS EQUIS ON EQUIS.SYSID=QVEQUIVALENCES.EQUIVALENTID
