CREATE VIEW QWINCLUSIONS AS
SELECT 
    QVINCLUSIONS.SYSID AS SYSID, 
    QVINCLUSIONS.PARENTID AS PARENTID, 
    QVINCLUSIONS.OBJECTID AS OBJECTID, 
    PARENTS.DESCRIPTION AS PARENTDESCR,
    CHILDREN.DESCRIPTION AS DESCRIPTION,
    QVINCLUSIONS.BEGINTIME AS BEGINTIME,
    QVINCLUSIONS.ENDTIME AS ENDTIME,
    QVINCLUSIONS.TAG AS TAG,
    QVINCLUSIONS.SORTER AS SORTER
FROM QVINCLUSIONS
INNER JOIN QVOBJECTS PARENTS  ON PARENTS.SYSID=QVINCLUSIONS.PARENTID
INNER JOIN QVOBJECTS CHILDREN ON CHILDREN.SYSID=QVINCLUSIONS.OBJECTID
