CREATE VIEW QWINCLCHILDREN AS
SELECT DISTINCT
    CHILDREN.SYSID AS SYSID, 
    PARENTS.SYSID AS PARENTID,
    CHILDREN.TYPOLOGYID AS TYPOLOGYID,
    CHILDREN.DESCRIPTION AS DESCRIPTION,
    CHILDREN.TAG AS TAG
FROM QVINCLUSIONS
INNER JOIN QVOBJECTS PARENTS  ON PARENTS.SYSID=QVINCLUSIONS.PARENTID
INNER JOIN QVOBJECTS CHILDREN ON CHILDREN.SYSID=QVINCLUSIONS.OBJECTID
