CREATE VIEW QWINCLPARENTS AS
SELECT DISTINCT
    QVINCLUSIONS.PARENTID AS SYSID, 
    CHILDREN.TYPOLOGYID AS TYPOLOGYID,
    PARENTS.DESCRIPTION AS DESCRIPTION,
    PARENTS.TAG AS TAG
FROM QVINCLUSIONS
INNER JOIN QVOBJECTS PARENTS  ON PARENTS.SYSID=QVINCLUSIONS.PARENTID
INNER JOIN QVOBJECTS CHILDREN ON CHILDREN.SYSID=QVINCLUSIONS.OBJECTID
