CREATE VIEW QWINCLBROWSER AS
SELECT DISTINCT
    CHILDREN.SYSID AS SYSID,
    QVINCLUSIONS.PARENTID AS PARENTID, 
    [:BOOL(QVINCLUSIONS.SYSID IS NOT NULL)] AS INCLUSIONS, 
    CHILDREN.DESCRIPTION AS DESCRIPTION,
    CHILDREN.TYPOLOGYID AS TYPOLOGYID,
    CHILDREN.BEGINTIME AS BEGINTIME,
    CHILDREN.ENDTIME AS ENDTIME,
    CHILDREN.TAG AS TAG
FROM QVOBJECTS CHILDREN
LEFT JOIN QVINCLUSIONS ON QVINCLUSIONS.OBJECTID=CHILDREN.SYSID
WHERE CHILDREN.DELETED=0
