CREATE VIEW QWOBJECTS AS
SELECT 
    SYSID,
    NAME,
    DESCRIPTION,
    REGISTRY,
    TYPOLOGYID,
    REFGENREID,
    BEGINTIME,
    ENDTIME,
    REFERENCE,
    CONSISTENCY,
    SCOPE,
    UPDATING,
    DELETING,
    TAG
FROM QVOBJECTS
WHERE DELETED=0