CREATE VIEW QWQUIVERIN AS
SELECT 
    QVARROWS.GENREID AS GENREID,
    QVARROWS.TARGETID AS OBJECTID,
    QVQUIVERARROW.QUIVERID AS QUIVERID, 
    SUM(QVARROWS.AMOUNT) AS AMOUNT
FROM QVARROWS
LEFT JOIN QVQUIVERARROW ON QVQUIVERARROW.ARROWID=QVARROWS.SYSID
WHERE QVARROWS.TARGETID<>'' AND QVARROWS.DELETED=0
GROUP BY QVQUIVERARROW.QUIVERID, QVARROWS.TARGETID, QVARROWS.GENREID
