CREATE VIEW QWQUIVERBROWSER AS
SELECT DISTINCT
    QVARROWS.SYSID AS SYSID,
    QVQUIVERARROW.QUIVERID AS QUIVERID,
    [:BOOL(QVQUIVERARROW.SYSID IS NOT NULL)] AS INCLUSIONS, 
    QVARROWS.DESCRIPTION AS DESCRIPTION,
    QVARROWS.TYPOLOGYID AS TYPOLOGYID,
    QVARROWS.GENREID AS GENREID,
    QVARROWS.MOTIVEID AS MOTIVEID,
    QVARROWS.BOWID AS BOWID,
    QVARROWS.TARGETID AS TARGETID,
    QVARROWS.AUXTIME AS AUXTIME,
    QVARROWS.AMOUNT AS AMOUNT,
    QVARROWS.TAG AS TAG
FROM QVARROWS
LEFT JOIN QVQUIVERARROW ON QVQUIVERARROW.ARROWID=QVARROWS.SYSID
WHERE QVARROWS.DELETED=0
