CREATE VIEW QWXBALANCES AS
SELECT 
EVENTTABLE.OBJECTID AS SYSID,
EVENTTABLE.GENREID AS GENREID,
EVENTTABLE.EVENTTIME AS EVENTTIME,
SUM(
CASE
WHEN EVENTTABLE.OBJECTID=QVARROWS.BOWID AND EVENTTABLE.OBJECTID=QVARROWS.TARGETID THEN 0
WHEN EVENTTABLE.OBJECTID=QVARROWS.TARGETID THEN QVARROWS.AMOUNT
WHEN EVENTTABLE.OBJECTID=QVARROWS.BOWID    THEN -QVARROWS.AMOUNT
ELSE 0
END
) AS BALANCE
FROM QWXEVENTS EVENTTABLE 
INNER JOIN QVARROWS ON 
    QVARROWS.GENREID=EVENTTABLE.GENREID AND (
        (QVARROWS.BOWID=EVENTTABLE.OBJECTID AND QVARROWS.BOWTIME<=EVENTTABLE.EVENTTIME) OR
        (QVARROWS.TARGETID=EVENTTABLE.OBJECTID AND QVARROWS.TARGETTIME<=EVENTTABLE.EVENTTIME)
    )
WHERE QVARROWS.STATUS>0 AND QVARROWS.AVAILABILITY<2 AND QVARROWS.CONSISTENCY=0 AND QVARROWS.DELETED=0
GROUP BY EVENTTABLE.OBJECTID, EVENTTABLE.GENREID, EVENTTABLE.EVENTTIME
